### ISSUE TITLE
Responsive 

### ISSUE THREAD

**Issue by ZiaCodes** [ZiaCodes/Lucy#6]
The website is not responsive for smaller devices like mobile and tablets.

**Comment by Ujjwal-Gupta-web** [comment]
Hey i would like to help in making this responsive.

**Comment by ZiaCodes** [comment]
> Hey i would like to help in making this responsive.

Yeah sure go ahead

**Comment by Ujjwal-Gupta-web** [comment]
made it responsive.

**Comment by ZiaCodes** [comment]
@Ujjwal-Gupta-web  yeah great job
